### ISSUE TITLE
Default device is not a removable drive (always D:?)

### ISSUE THREAD

**Issue by Zastai** [phw/dotnet-discid#2]
Not sure if this is libdiscid or dotnet-discid at fault, but Disc.DefaultDevice returns D: even though drives C-F are hard disks. It should be easy to use the first removable drive instead (perhaps easier for the .NET bindings than for libdiscid, depending on the level of WinAPI use).

**Comment by phw** [comment]
That's due to the libdiscid version shipped with the nuget package (0.5.1). That behavior was the default on Windows until that version, it was fixed in libdiscid 0.5.2, see https://github.com/metabrainz/libdiscid/pull/20 

You should be able to just update the discid.dll, see https://musicbrainz.org/doc/libdiscid .  Unfortunately there are only 32bit builds available from official sources, but I would recommend using those anyway, the 64bit version is not as well tested on Windows. But if you need 64bit you can build it yourself.

I will keep this ticket open and update the version included in the nuget package, but this will take me some time. Not sure if I will fix this during the holidays.

**Comment by phw** [comment]
This was fixed by PR #3
